### PR TITLE
persist computation statistics across executions

### LINKED ISSUE #97: Feature request for more stats...
Hi,

I just want a few features which I hope would be easy to implement:

1. Persistent statistics
 a. Total number of games analyzed since installed, broken down by type (chess, crazyhouse, etc)
 b. Average time to analyze a whole game (not position)
 c. Average number of moves per game

2. Per session statistics
 a. Total games analyzed
 b. Time running

Thanks!

### PR DESCRIPTION
**Pull request by eEQK**
partially resolves #97

Personally I think sqlite is a bit of an overkill here but adding it at this point isn't really a problem. What are your thoughts on this?

### CODE REVIEW

**Comment by niklasf** [comment]
Thanks. A couple points:

* We already use `serde` and `serde_json` elsewhere, so we might as well write JSON rather a custom serialization format.
* I think it's best to save only batches, positions, and nodes. We don't really know if anything changed (maybe even the entire configuration), so it's better to start again with a conservative estimate for nodes per second.
* As of now, the working directory for the generated systemd service is `/tmp`, so stats would frequently be lost. I wonder what's the appropriate place to put something like this on Linux (and Windows and MacOS).
* Failing to read or write stats should probably log a warning and then continue, not panic.

**Comment by jirislav** [comment]
Hi, how's the status of this PR? The work looks promising, I'd certainly welcome the stats .. maybe it would be also good, to publish collected metrics to be scraped by Prometheus? I have monitoring infrastructure and it could be interesting to look at the data.

Currently, I'm collecting only generic container data, see the motivational screenshot:
image

**Comment by eEQK** [comment]
@niklasf I think I've resolved all of your suggestions. 

I'm not sure if the names I've assigned to functions are accurate/aligned with rust conventions, let me know if that's the case or if there are any issues with my code.

**Comment by niklasf** [comment]
Thanks. Looks good on first glance. I'll merge it soonish.

**Comment by niklasf** [comment]
Yep, this is great. Will make a release soon.

**Comment by niklasf** [comment]
Included in v2.3.0. Thanks again!

**Pull request merged**
