### PR TITLE
Enable avx512 and vnni512 builds for stockfish

### PR DESCRIPTION
**Pull request by kdave**
Add detection of the AVX512 based features and build stockfish with that.
The vnni256 build is not done as it's the same as vnni512 but with
preferred register width 256. The CPU flags are the same so this cannot
be detected automatically and would have to be selected by user. Given the
results below it does not significantly improve things so it's probably
not worth the effort.

I've tested the build locally with fishnet client, subjectively the
reported knps increased by about 1000 but you don't have to believe
that.

Stockfish benchmark shows a minor NPS improvement for the accelerated
builds compared to BMI2, and if not at least it's not worse.
Sample short tc tournaments and and estimated Elo, calculated by ordo:

tc 1+1, 40 games

    # PLAYER        :  RATING  POINTS  PLAYED   (%)
    1 sf-bmi2       :  2317.6     8.5      16    53
    2 sf-vnni512    :  2317.6     8.5      16    53
    3 sf-vnni256    :  2317.6     8.5      16    53
    4 sf-avx2       :  2282.4     7.5      16    47
    5 sf-avx512     :  2264.7     7.0      16    44

tc 10+0.1, 40 games

    # PLAYER        :  RATING  POINTS  PLAYED   (%)
    1 sf-vnni512    :  2354.0     9.5      16    59
    2 sf-avx2       :  2335.9     9.0      16    56
    3 sf-vnni256    :  2318.0     8.5      16    53
    4 sf-avx512     :  2264.3     7.0      16    44
    5 sf-bmi2       :  2227.8     6.0      16    38

tc 10+1, 40 games

    # PLAYER        :  RATING  POINTS  PLAYED   (%)
    1 sf-avx2       :  2317.6     8.5      16    53
    2 sf-vnni512    :  2300.0     8.0      16    50
    3 sf-avx512     :  2300.0     8.0      16    50
    4 sf-bmi2       :  2300.0     8.0      16    50
    5 sf-vnni256    :  2282.4     7.5      16    47

### CODE REVIEW

**Comment by niklasf** [comment]
Thanks, looks good.

Looks like it's currently failing in CI. Maybe a newer compiler version is required?

**Comment by kdave** [comment]
The rust version should be ok, It fails on `rustc 1.57.0 (f1edd0429 2021-11-29)` in CI, I've been running a 1.57-based version and gcc/g++ 11.2.1. I can't see what exactly is the version on the CI host, but it seems to lack support for the `vnni` features, `g++: error: unrecognized command line option ‘-mavx512vnni’; did you mean ‘-mavx5124vnniw’?`.

**Comment by kdave** [comment]
The CI image is based on ubuntu 18.04, and I see version 7.5 and 8.4 available there. Some VNNI support is announced for gcc 8, I can't find the exact version. Anyway, updating the CI image to ubuntu 20.x should fix and maybe prevent more build issues.

**Comment by niklasf** [comment]
Unfortunately I can't just update the image, because then Stockfish will be built with the glibc of the newer Ubuntu and the created binary releases will no longer be compatible with older Ubuntu versions. I'll look into installing a newer gcc on the old Ubuntu image.

**Comment by niklasf** [comment]
Linux build works after updating to g++ 11. Looking into Windows, next ...

**Comment by kdave** [comment]
I haven't added the windows targets because I can't test it but you have a CI it should at least catch build problems. As you've probably fixed the CI environment, I'll add the windows binaries and add the Fairy-Stockfish builds too.

**Comment by kdave** [comment]
I've pushed the windows assets for stockfish and fairy-stockfish for both linux and windows. Let me know if you want to reorganize the commits. I did only linux build tests, the CI should verify windows build.

**Comment by niklasf** [comment]
The Windows build is failing with these messages :thinking:

```
  C:\Users\RUNNER~1\AppData\Local\Temp\ccwZIdwf.s: Assembler messages:
  C:\Users\RUNNER~1\AppData\Local\Temp\ccwZIdwf.s:3159: Error: invalid register for .seh_savexmm
  C:\Users\RUNNER~1\AppData\Local\Temp\ccwZIdwf.s:3161: Error: invalid register for .seh_savexmm
  C:\Users\RUNNER~1\AppData\Local\Temp\ccwZIdwf.s:3163: Error: invalid register for .seh_savexmm
  C:\Users\RUNNER~1\AppData\Local\Temp\ccwZIdwf.s:3165: Error: invalid register for .seh_savexmm
  C:\Users\RUNNER~1\AppData\Local\Temp\ccwZIdwf.s:3167: Error: invalid register for .seh_savexmm
  C:\Users\RUNNER~1\AppData\Local\Temp\ccwZIdwf.s:3169: Error: invalid register for .seh_savexmm
  C:\Users\RUNNER~1\AppData\Local\Temp\ccwZIdwf.s:3171: Error: invalid register for .seh_savexmm
  mingw32-make[1]: *** [<builtin>: tbprobe.o] Error 1
  mingw32-make: *** [Makefile:746: build] Error 2
```

**Comment by kdave** [comment]
https://stackoverflow.com/questions/43152633/invalid-register-for-seh-savexmm-in-cygwin says it can be fixed by adding `-fno-asynchronous-unwind-tables`, fixed upstream https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65782 .

**Comment by niklasf** [comment]
Updating the version on the CI runner is tricky, but the workaround appears to do the trick. Ready to merge now. Thanks!

**Pull request merged**
