### PR TITLE
Change backlog waiting logic

### PR DESCRIPTION
**Pull request by bharrisau**
Uses exponential backoff logic to wait when the work backlog is less than configured. The previous logic caused much more traffic when wait times were just over 1 second.

### CODE REVIEW

**Comment by bharrisau** [comment]
If someone has set their backlogs to 2hours or something (super low priority) - they would now be pinging every 30 seconds instead of every 2 hours as previously. They would need to update the config file to set `max_backoff` to 2 hours. The default laptop config has 30 seconds for `userbacklog`, so the default 30 seconds `max_backoff` is good.

**Comment by bharrisau** [comment]
On further review - the wait should be `max(wait, backoff)` - if the config says a minimum of 30 seconds queue length, and the queue is currently at 0 seconds - then it clearly needs to wait at least 30 seconds for the queue to have a chance of being that old.

**Comment by niklasf** [comment]
Also see the `Acquire::NoContent` branch below. So essentially what it does currently is `wait + backoff`. I guess `max(wait, backoff)` would really be more precise.

**Comment by bharrisau** [comment]
> So essentially what it does currently is `wait + backoff`.

If I'm reading it right, it does `wait or backoff` - as the wait section finishes with `continue` so repeats the `backlog_wait_time` which calls `Status` again to check the queue length.

In the current impl if `systembacklog` and `userbacklog` are set to 1 (maybe you only want to contribute when there is a 1 second queue) - there will be a request to the `https://lichess.org/fishnet/status` endpoint once per second. In the proposed the wait times will be 1 second for 2 to 3 attempts, then the exponential will start to take effect.

I modified the logging to use `INFO` when the wait is 1 minute or longer. And also applied that to the `Acquire::NoContent` too. Not sure if that change is ok - I was just trying to standardise between them without adding too much noise. I'm assuming most people run 0 for the backlog so will never hit the 'Not enough backlogged jobs' and they use the standard 30s `max_backoff` so never get the INFO messages.

```sh
# Previous
D: User wait: 3s due to 3s for oldest 0ns, system wait: 1s due to 1s for oldest 0ns
D: Going idle for 1s.
D: User wait: 3s due to 3s for oldest 0ns, system wait: 1s due to 1s for oldest 0ns
D: Going idle for 1s.
D: User wait: 3s due to 3s for oldest 0ns, system wait: 1s due to 1s for oldest 0ns
D: Going idle for 1s.
D: User wait: 3s due to 3s for oldest 0ns, system wait: 1s due to 1s for oldest 0ns
D: Going idle for 1s.

# Proposed
D: User wait: 3s due to 3s for oldest 0ns, system wait: 1s due to 1s for oldest 0ns
D: Not enough backlogged jobs. Backing off 1s.
D: User wait: 3s due to 3s for oldest 0ns, system wait: 1s due to 1s for oldest 0ns
D: Not enough backlogged jobs. Backing off 1s.
D: User wait: 3s due to 3s for oldest 0ns, system wait: 1s due to 1s for oldest 0ns
D: Not enough backlogged jobs. Backing off 2.014s.
D: User wait: 3s due to 3s for oldest 0ns, system wait: 1s due to 1s for oldest 0ns
D: Not enough backlogged jobs. Backing off 6.324s.
D: User wait: 3s due to 3s for oldest 0ns, system wait: 1s due to 1s for oldest 0ns
D: Not enough backlogged jobs. Backing off 6.075s.
D: User wait: 3s due to 3s for oldest 0ns, system wait: 1s due to 1s for oldest 0ns
D: Not enough backlogged jobs. Backing off 5.499s.
D: User wait: 3s due to 3s for oldest 0ns, system wait: 1s due to 1s for oldest 0ns
D: Not enough backlogged jobs. Backing off 9.668s.
D: User wait: 3s due to 3s for oldest 0ns, system wait: 1s due to 1s for oldest 0ns
D: Not enough backlogged jobs. Backing off 25.23s.
```

**Comment by niklasf** [comment]
Thanks, I think it makes sense to unify these, if possible, but it is a bit tricky.

The `max(backoff, wait)` is now under a branch with `wait >= 1s`, so now it would never apply the backoff if `--user-backlog 0`.

When the backoff was applied elsewhere, this condition was only to prevent hammering the status endpoint with greater frequency. But now we cannot just remove it, or else it would never even get past the `continue`.

**Pull request closed without merging**
