### PR TITLE
make lower levels play fewer silly moves

### PR DESCRIPTION
**Pull request by ornicar**

### CODE REVIEW

**Comment by niklasf** [comment]
Current progression: [0, 3, 6, 9, 11, 14, 17, 20]
Proposal: [3, 6, 9, 11, 14, 17, 20, 20]

Is it intended to seperate lvl 7 and 8 only by movetime?

Current lvl 1 is quite a challenge for absolute beginners. Should we keep it at SF lvl 0?

**Comment by ddugovic** [comment]
Given that proposal, greatly increasing the AI level 8 depth ceiling might be interesting.

On the other hand, I agree AI level 1 is quite a challenge for absolute beginners.  Not sure which levels we mean by "lower levels".

**Comment by ornicar** [comment]
https://lichess.org/forum/lichess-feedback/cpu-malfunction#1

I tried level 5 too and could win without thinking much.

**Comment by ddugovic** [comment]
https://lichess.org/Zga3wmks/black#85
https://lichess.org/Gx7re8Dw/black#117

Possible cause? 1de4a276c50642cad105c9d5aed27a8b4cf38b06

**Comment by ornicar** [comment]
Lichess sends `clock: null` to fishnet in the move JSON

**Comment by niklasf** [comment]
Looks like that's handled correctly. In a local test search in lichess lvl 5 is almost always cut off by depth, not movetime nor time management.

We don't have to find a formula. How about non-linear skills like [0, 3, 6, 10, 14, 16, 18, 20]?

> Given that proposal, greatly increasing the AI level 8 depth ceiling might be interesting.

And mabye that, too, to differentiate it even more.

**Comment by ddugovic** [comment]
With further research, I suppose this isn't a regression - last year AI level 5 had similar mistake rates:
https://lichess.org/T5EDuF2n

I agree we don't need a formula.

**Pull request closed without merging**
