### PR TITLE
Add Dockerfile for new binary

### PR DESCRIPTION
**Pull request by teotwaki**
As per https://github.com/niklasf/fishnet/issues/130.

### CODE REVIEW

**Comment by teotwaki** [comment]
Moving forward I would recommend you create a Docker Hub account, add the credentials to the GitHub secrets, and that way I could offer some PRs so that the GitHub Workflow builds and pushes the Docker images to Docker Hub.

In my opinion, the docker images shouldn't auto-update (or at least, not "just like that"). I think it would make better sense to just push the new images whenever they're available, and let the people running them manage the update (watchtower and things like that already automate this process).

**Comment by ndurchx** [comment]
I would prefer a Dockerfile, which is using the source to make fresh builds. Like in PR #132

**Comment by thesilican** [comment]
Docker Hub has features that allows you to auto-build containers whenever a GitHub repository updates.

You can configure it to build whenever a commit is pushed, or when a tag is added.

I use the following build rule for my own projects, it auto-builds a docker image whenever a commit has a version tag (e.g. v1.0.0)

image

**Comment by teotwaki** [comment]
> I would prefer a Dockerfile, which is using the source to make fresh builds.

That's of course a valid alternative. I asked in https://github.com/niklasf/fishnet/issues/130 and no preference was given. Please note that the referenced PR has a number of issues:

- it doesn't strip binaries
- it includes the entire build toolchain
- it doesn't use environment variables for configuration.

@thesilican So they run the infrastructure that builds your image? That's handy. Thanks a lot for the info.

@niklasf I can make the changes to the Dockerfile so that it builds from source, if that's the consensus. Let me know what you prefer.

**Comment by thesilican** [comment]
Here are some of my 2-cents:
- Building from source is much better as it ties each build to the source code, and doesn't rely on pulling from GitHub repo (which possibly could change before or during the container build)
- Don't auto-update from within the container, users should instead pull updated images
- Make sure to include a `.dockerignore` file so local build files/config is ignored (Easiest is to just use contents of `.gitignore`)
- I suggest to change env `FISHNET_API_KEY` to just `API_KEY` as `FISHNET_` is a bit redundant. But either way is fine really

Here's a possible Dockerfile snippet that builds from source:
```dockerfile
# Use specific version to prevent build from breaking if rust updates
# Update as necessary
FROM rust:1.48 AS builder

WORKDIR /fishnet

COPY . .
# Clone git submodules before building
RUN git submodule update --init --recursive
RUN cargo build --release

# Not using alpine due to https://andygrove.io/2020/05/why-musl-extremely-slow/
FROM debian:buster-slim

COPY --from=builder /fishnet/target/release/fishnet /fishnet

# ... put whatever else is necessary
```

**Comment by niklasf** [comment]
Looks good, and I like building from source after all, especially with the easier dockerhub integration.

**Pull request closed without merging**
