### PR TITLE
allow to define maximal amount of seconds to wait before next job

### PR DESCRIPTION
**Pull request by eronnen**

### CODE REVIEW

**Comment by niklasf** [comment]
Hi, thanks for the pull request. Can you please explain the purpose of this patch a bit? Is your client idle too long?

**Comment by eronnen** [comment]
I was running 2 instances of fishnet on my local developement environment, so i had to wait almost 30 seconds until one of them actually made a move...
also when I played bullet they flagged some of the times, probably because they sleep for 2-3 seconds if I don't make any move for a couple of seconds even if they have only few seconds left. 
What do you think about optimizing the backoff time to be sort of "exponential" sequence which increases at smaller steps initially and only after a lot of requests will increase faster?

**Comment by niklasf** [comment]
Makes sense. Merging, and we can tweak it from there. I don't think with the current design it will ever be great for volume play, but it can certainly be improved a bit.

**Comment by niklasf** [comment]
I'll rename this to `--max-backoff` and accept values like `500ms` before the next release.

**Pull request merged**
