### PR TITLE
Use UCI_Elo and retire depth restriction

### PR DESCRIPTION
**Pull request by ddugovic**
Not yet tested.  Attempts to help solve https://github.com/ornicar/lila/issues/6482

Values copied from https://github.com/ornicar/lila/blob/5488a09548a7ae32674065d39a9491ef8d59de3b/modules/fishnet/src/main/AiPerf.scala

### CODE REVIEW

**Comment by ianfab** [comment]
Was the effect on playing strength measured already? The UCI_Elo parameter is aligned with CCRL ratings and they are usually quite deflated below 2000, so I am not sure whether the reduced Skill Level can compensate for the removal of the depth limit.

**Comment by niklasf** [comment]
I am currently running a small tournament (not enough games for useful Elo estimates), and the iterim results were enough to convince me that the new negative skill levels are significantly weaker. However this is at equal time controls.

I misunderstood https://github.com/official-stockfish/Stockfish/blob/3af083a7cd9be1659f1d8a39a65e33b87608f762/src/search.cpp#L500-L502
and thought that the depth limits were mostly useless. Now I am not so sure, so it will need some more testing.

**Comment by niklasf** [comment]
I played some games against it, and it certainly feels much weaker. I brought back some basic depth limits regardless, just to limit resource consumption (https://github.com/niklasf/fishnet/commit/d1c1afe706d74673f1b754365ac29e7aee5a4ce6).

**Comment by jim-perkins** [comment]
I read on the forums where the fishnet was restarted for this upgrade and checked my running instance of fishnet.  I determined neither stockfish nor fishnet had been updated.  I restarted fishnet and stockfish was updated but fishnet was not.   Determined that fishnet wasnt updated because I am using a git version of fishnet,  not a version installed thru pip.

question is would this cause a problem using a mismatched version of stockfish/fishnet .  I did see these changes which is what got me wondering .  LVL_DEPTHS = [5, 5, 5, 5, 5, 8, 13, 22]

Probably very few people are running the git version of fishnet.  Right now I am following fishnet so manually updating isnt an issue.  Just concerned that if I failed to update fishnet and stockfish was updated it would cause a problem with the system.  

Open to suggestions.  Maybe I should just use the pip version of fishnet and be done with it  but I wanted to be able to run the latest fishnet .  thanks

**Comment by niklasf** [comment]
There is no need to do anything on your side. This change only affects a handful of fishnet clients run by Lichess. Third-party fishnet clients are only used for analysis, not play, to keep move latencies down.

**Pull request merged**
