### PR TITLE
Integrate Watkins antichess solution for analysis

### PR DESCRIPTION
**Pull request by ddugovic**
Watkins is efficient at providing known solutions and `nodes` indicating how complex a solution is.

This is an initial attempt to integrate and makes no attempt at calculating the DTM, instead using `mate 500` to indicate White is winning in at most 500 moves.

### CODE REVIEW

**Comment by niklasf** [comment]
Cool show case. In a production environment lila should probably query the server directly. But this would only intrest a relatively small number of players, so it's probably not gonna land :(

**Comment by ProgramFOX** [comment]
Now I wonder, would having this imply that all non-1.e3 moves (or all non-Watkins moves for that matter) will be counted as blunder?

**Comment by niklasf** [comment]
The way it was built here, yes.

But actually we do not know if for example 1. g3 also wins. So it wouldn't be fair to call that move a blunder.

**Comment by ddugovic** [comment]
Right, and by the way it's possible that unless given an unlimited amount of time to analyze, Stockfish may mis-evaluate won or lost positions.

Currently Lichess cloud analysis is only used for standard chess.

**Pull request closed without merging**
